openapi: 3.0.0
info:
    title: Collector API
    version: 1.0.0
    description: |
        REST API for managing fetchers within Collector API.
servers:
    - url: /
paths:
    /health:
        get:
            tags:
                - Health
            summary: Health check
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string

components:
    schemas:
