export enum FetchStatus {
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    UNAVAILABLE = 'UNAVAILABLE',
    FAILED = 'FAILED',
}

export enum FetchUnavailabilityReason {
    PAST_SNAPSHOT_NOT_CAPTURED = 'PAST_SNAPSHOT_NOT_CAPTURED',
    HISTORICAL_DATA_NOT_AVAILABLE = 'HISTORICAL_DATA_NOT_AVAILABLE',
}
